language: go
env:
  TRAVIS_BUILD=true
go:
  - 1.6
  - 1.7
  - master
services:
  - postgresql
install:
  - ./prepare_version.sh
  - go get github.com/beego/bee
  - go get github.com/tools/godep
  - go get gopkg.in/testfixtures.v1
  - go get github.com/astaxie/beego/migration
  - godep get
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
before_script:
  - psql -c 'create database summercamp_test;' -U postgres
  - ./migrate.sh "" -m travis
script:
  - gometalinter --disable-all --enable=vet --enable=vetshadow && go test ./tests/... && bee pack