language: go

go:
  - 1.6
  - 1.7
  - master
install:
  - go get github.com/astaxie/beego
  - go get github.com/beego/bee
  - go get -u github.com/alecthomas/gometalinter
script:
  - gometalinter ./... && bee pack