version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=summercamp
      - POSTGRES_PASSWORD=q1w2e3r4
  web-build:
    build: .
    environment:
      - SUMMERCAMP_CONTAINER_OBJECTIVE=test_and_build
    volumes:
      - ../:/go/src/github.com/Frozen-Team/summercamp/
      - ./build:/tmp/build
    ports:
      - "8082:8080"
    depends_on:
      - db
  web-run:
    build: .
    environment:
      - SUMMERCAMP_CONTAINER_OBJECTIVE=run
    volumes:
      - ../:/go/src/github.com/Frozen-Team/summercamp/
    ports:
      - "8082:8080"
    depends_on:
      - db