version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=summercamp_test
      - POSTGRES_PASSWORD=q1w2e3r4
  web:
    build: .
    volumes:
      - ../:/go/src/github.com/Frozen-Team/summercamp/
      - ./build:/tmp/build
    ports:
      - "8082:8080"
    depends_on:
      - db